Changed the yml too with correct url

diff --git a/.github/workflows/run-app.yml b/.github/workflows/run-app.yml
--- a/.github/workflows/run-app.yml
+++ b/.github/workflows/run-app.yml
@@ -25,4 +25,4 @@ jobs:
         run: nohup node index.js &
 
       - name: Health Check
-        run: curl --fail http://localhost:1100/login || exit 1 #curl either returns success (0) or non-zero which will be converted to 1
+        run: curl --fail http://localhost:1100/health || exit 1 #curl either returns success (0) or non-zero which will be converted to 1
